### ISSUE TITLE
GI3

### ISSUE THREAD

**Issue by englishworder** [Razmoth/MetadataConverter2#1]
how much they changed?
may i know some details?
3.6 global-metadata.dat https://mega.nz/file/VD9zTLbC#gAPyVboajcydOVzRNwoOfLELJ_2pV865ooz_8Yfk60o

**Comment by Razmoth** [comment]
Greetings,

Since version 3.2 and newer, `global-metadata.dat` has been changed to `MHY\x0` structure, were static dumping got broken.
