### ISSUE TITLE
nothing

### ISSUE THREAD

**Issue by YuroGod** [Razmoth/MetadataConverter2#2]
![image](https://github.com/RazTools/Metadata/assets/81439014/d1b861b2-851d-4f40-84e7-1721b185dc6b)

**Comment by SleepyAsh0191** [comment]
remember to use SRV2 and use gameassembly_patched.dll

**Comment by YuroGod** [comment]
> 记得用SRV2，用gameassembly_patched.dll

thanks bro🥰

**Comment by Tubitu** [comment]
> 

![image](https://github.com/RazTools/Metadata/assets/81439014/524136c6-e331-485e-9e88-d721490dd5cf)
why😥

**Comment by MoonShadowIllusion** [comment]
> remember to use SRV2 and use gameassembly_patched.dll

哪有 gameassembly_patched.dll

**Comment by SleepyAsh0191** [comment]
> > remember to use SRV2 and use gameassembly_patched.dll
> 
> 
> 
> 哪有 gameassembly_patched.dll

本工具已不再适用于1.5之后的崩铁
