### ISSUE TITLE
HSR 1.6 Metadata

### ISSUE THREAD

**Issue by YunliBeta** [Razmoth/MetadataConverter2#4]
<img width="855" alt="image" src="https://github.com/RazTools/Metadata/assets/104631604/3ad81c01-b3a1-4e1f-bf69-d3ff1dbd65cf">
HSR 1.6 Metadata not working, while all previous versions worked.

**Comment by Razmoth** [comment]
Greetings,

Newer versions have changed and are not planned to be supported.
